test

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -135,36 +135,35 @@ stages:
     environment: 'deploy'
     strategy:
       runOnce:
-        deploy:
-          steps:
-          - script: |
-              # Cd to terraform folder.
-              pwd
-              ls -al
-              cd terraform/app
-              export TF_VAR_tag=$(echo $BUILD_BUILDNUMBER)
-              printenv
-              pwd
-              ls -al   
-              # Exit when any command returns a failure status.
-              set -e
-              # Write terraform.tfvars.
-              echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform-app.tfvars
-              # Write backend.tfvars.
-              echo 'resource_group_name = "tf-storage-rg"' | tee backend-app.tfvars
-              echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend-app.tfvars
-              echo 'container_name = "tfstate"' | tee -a backend-app.tfvars
-              echo 'key = "terraform.tfstate-app"' | tee -a backend-app.tfvars
-              # Initialize Terraform.
-              terraform init -input=false -backend-config="backend-app.tfvars"
-              # Apply the Terraform plan.
-               terraform apply -input=false -auto-approve
+        steps:
+        - script: |
+            # Cd to terraform folder.
+            pwd
+            ls -al
+            cd terraform/app
+            export TF_VAR_tag=$(echo $BUILD_BUILDNUMBER)
+            printenv
+            pwd
+            ls -al   
+            # Exit when any command returns a failure status.
+            set -e
+            # Write terraform.tfvars.
+            echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform-app.tfvars
+            # Write backend.tfvars.
+            echo 'resource_group_name = "tf-storage-rg"' | tee backend-app.tfvars
+            echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend-app.tfvars
+            echo 'container_name = "tfstate"' | tee -a backend-app.tfvars
+            echo 'key = "terraform.tfstate-app"' | tee -a backend-app.tfvars
+            # Initialize Terraform.
+            terraform init -input=false -backend-config="backend-app.tfvars"
+            # Apply the Terraform plan.
+             terraform apply -input=false -auto-approve
       
-            name: 'RunTerraform'
-            displayName: 'Run Terraform'
-            env:
-              TF_VAR_arm_client_id: $(ARM_CLIENT_ID)
-              TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET)
-              TF_VAR_arm_tenant_id: $(ARM_TENANT_ID)
-              TF_VAR_arm_subscription_id: $(ARM_SUBSCRIPTION_ID)
-              TF_VAR_db_pass: $(DB_PASS)
+          name: 'RunTerraform'
+          displayName: 'Run Terraform'
+          env:
+            TF_VAR_arm_client_id: $(ARM_CLIENT_ID)
+            TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET)
+            TF_VAR_arm_tenant_id: $(ARM_TENANT_ID)
+            TF_VAR_arm_subscription_id: $(ARM_SUBSCRIPTION_ID)
+            TF_VAR_db_pass: $(DB_PASS)
