test deploy to prod

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -118,22 +118,9 @@ stages:
   displayName: 'Deploy App'
   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/terraform'))
   jobs:
-  - job: "waitForValidation"
-    displayName: "Wait > Wait for manual appoval"
-    pool: "server"
-    timeoutInMinutes: "2" # job times out in 3 days
-    steps:
-      - task: ManualValidation@0
-        timeoutInMinutes: "1" # task times out in 1 day
-        inputs:
-          notifyUsers: |
-                           vitalii_brazhaev@epam.com
-          instructions: "There are resources being destroyed as part of this deployment, please review the output of Terraform plan before approving."
-          onTimeout: "reject"
 
   - job:  Deploy_to_Dev
     displayName: 'Deploy to Dev'
-    dependsOn: "waitForValidation"
     pool:
       vmImage: 'ubuntu-18.04'
     steps:
@@ -164,3 +151,50 @@ stages:
         TF_VAR_registry_url: $(registryUrl)
         TF_VAR_values_name: values.dev
         TF_VAR_namespace: develop
+
+  - job: "waitForValidation"
+    displayName: "Wait > Wait for manual appoval"
+    pool: "server"
+    timeoutInMinutes: "5" # job times out in 3 days
+    steps:
+      - task: ManualValidation@0
+        timeoutInMinutes: "3" # task times out in 1 day
+        inputs:
+          notifyUsers: |
+                           vitalii_brazhaev@epam.com
+          instructions: "There are resources being destroyed as part of this deployment, please review the output of Terraform plan before approving."
+          onTimeout: "reject"
+
+  - job:  Deploy_to_Prod
+    displayName: 'Deploy to Prod'
+    dependsOn: "waitForValidation"
+    pool:
+      vmImage: 'ubuntu-18.04'
+    steps:
+    - script: |
+        # Cd to terraform folder.
+        
+        cd terraform/app
+        export TF_VAR_tag=$(echo $BUILD_BUILDNUMBER)
+        printenv   
+        # Exit when any command returns a failure status.
+        set -e
+        # Write terraform.tfvars.
+        echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform-app.tfvars
+        # Write backend.tfvars.
+        echo 'resource_group_name = "tf-storage-rg"' | tee backend-app.tfvars
+        echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend-app.tfvars
+        echo 'container_name = "tfstate"' | tee -a backend-app.tfvars
+        echo 'key = "terraform.tfstate-app"' | tee -a backend-app.tfvars
+        # Initialize Terraform.
+        terraform init -input=false -backend-config="backend-app.tfvars"
+        # Apply the Terraform plan.
+         terraform apply -input=false -auto-approve
+
+      name: 'RunTerraform'
+      displayName: 'Run Terraform'
+      env:
+        TF_VAR_db_pass: $(DB_PASS)
+        TF_VAR_registry_url: $(registryUrl)
+        TF_VAR_values_name: values.prod
+        TF_VAR_namespace: production
