test app

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -65,7 +65,7 @@ stages:
         printenv
 
         # Destroy the Terraform plan.
-        # terraform destroy -input=false -auto-approve
+        #terraform destroy -input=false -auto-approve
 
       name: 'RunTerraform'
       displayName: 'Run Terraform'
@@ -81,7 +81,20 @@ stages:
 - stage: 'Build'
   displayName: 'Build application'
   condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/terraform'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
-  jobs: 
+  jobs:
+  - job: "waitForValidation"
+    displayName: "Wait > Wait for manual appoval"
+    pool: "server"
+    timeoutInMinutes: "4320" # job times out in 3 days
+    steps:
+      - task: ManualValidation@0
+        timeoutInMinutes: "1440" # task times out in 1 day
+        inputs:
+          notifyUsers: |
+                           vitalii_brazhaev@epam.com
+          instructions: "There are resources being destroyed as part of this deployment, please review the output of Terraform plan before approving."
+          onTimeout: "reject"
+
   - job: Build_Image
     displayName: 'Build job image'
     pool:
@@ -128,42 +141,36 @@ stages:
   displayName: 'Deploy App'
   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/terraform'))
   jobs:
-  - deployment:  Deploy_to_Dev
+  - job:  Deploy_to_Dev
     displayName: 'Deploy to Dev'
     pool:
       vmImage: 'ubuntu-18.04'
-    environment: 'deploy'
-    strategy:
-      runOnce:
-        steps:
-        - script: |
-            # Cd to terraform folder.
-            pwd
-            ls -al
-            cd terraform/app
-            export TF_VAR_tag=$(echo $BUILD_BUILDNUMBER)
-            printenv
-            pwd
-            ls -al   
-            # Exit when any command returns a failure status.
-            set -e
-            # Write terraform.tfvars.
-            echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform-app.tfvars
-            # Write backend.tfvars.
-            echo 'resource_group_name = "tf-storage-rg"' | tee backend-app.tfvars
-            echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend-app.tfvars
-            echo 'container_name = "tfstate"' | tee -a backend-app.tfvars
-            echo 'key = "terraform.tfstate-app"' | tee -a backend-app.tfvars
-            # Initialize Terraform.
-            terraform init -input=false -backend-config="backend-app.tfvars"
-            # Apply the Terraform plan.
-             terraform apply -input=false -auto-approve
-      
-          name: 'RunTerraform'
-          displayName: 'Run Terraform'
-          env:
-            TF_VAR_arm_client_id: $(ARM_CLIENT_ID)
-            TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET)
-            TF_VAR_arm_tenant_id: $(ARM_TENANT_ID)
-            TF_VAR_arm_subscription_id: $(ARM_SUBSCRIPTION_ID)
-            TF_VAR_db_pass: $(DB_PASS)
+    steps:
+    - script: |
+        # Cd to terraform folder.
+        
+        cd terraform/app
+        export TF_VAR_tag=$(echo $BUILD_BUILDNUMBER)
+        printenv   
+        # Exit when any command returns a failure status.
+        set -e
+        # Write terraform.tfvars.
+        echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform-app.tfvars
+        # Write backend.tfvars.
+        echo 'resource_group_name = "tf-storage-rg"' | tee backend-app.tfvars
+        echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend-app.tfvars
+        echo 'container_name = "tfstate"' | tee -a backend-app.tfvars
+        echo 'key = "terraform.tfstate-app"' | tee -a backend-app.tfvars
+        # Initialize Terraform.
+        terraform init -input=false -backend-config="backend-app.tfvars"
+        # Apply the Terraform plan.
+         terraform apply -input=false -auto-approve
+
+      name: 'RunTerraform'
+      displayName: 'Run Terraform'
+      env:
+        TF_VAR_arm_client_id: $(ARM_CLIENT_ID)
+        TF_VAR_arm_client_secret: $(ARM_CLIENT_SECRET)
+        TF_VAR_arm_tenant_id: $(ARM_TENANT_ID)
+        TF_VAR_arm_subscription_id: $(ARM_SUBSCRIPTION_ID)
+        TF_VAR_db_pass: $(DB_PASS)
